### PR TITLE
Updated Account to latest fields, supporting more account preferences, updated Post edit to include languge

### PR DESCRIPTION
**Pull request by technicat**
Added noindex, indexable, hideCollections, and role to Account, which supports opting in/out of search and hiding follower/followee info from the  public, and updated/added TootSource and TootRole accordingly (see added test cases for reference)

Also fixed missing snake case mapping in PostEditParams which was losing spoilers and attachments.

### CODE REVIEW

**Comment by technicat** [comment]
fixes #268

**Comment by kkostov** [comment]
@technicat That's quite the change! Thank you so much 🙌

✅ `indexable`, `noindex` and `hideCollections` looks good.

✅ `EditPostParams` looks good.

✅ `TootSource` looks good.

✅ `UpdateCredentialsParams` looks good.

✅ 🎉 Unit Tests ❤️


Regarding the `role` field, I think we need a little bit more to support it. Can we take it out of this PR?

Some thoughts: `Pleroma` uses "roles" as an object with a boolean field for "admin" or "moderator" which we can handle during serialization. I like the `TootRole` concept, perhaps we could simplify this object a bit to allow us to fill-in values when coming from other flavours (e.g. remove the `id` field, and change `color`, `permissions` and `highlighted` to Optional) Also, Mastodon only returns a role for "CredentialAccount", not regular "Account" so we should consider creating a dedicated model for the endpoints which actually return a role field.

**Comment by kkostov** [comment]
@technicat On second thought, I'm OK to merge this if we can simplify `TootRule` so tweaking the serialization for pleroma will not cause too much breakage.

**Comment by kkostov** [comment]
@technicat On second, second thought 😅, it seems supporting the Admin API calls for Pleroma/Akkoma's roles will be very much a dedicated effort as they require an entirely specific set of endpoints and models. Let's go with the Mastodon's role for now.

**Review by kkostov — APPROVED** [review]

**Review by davidgarywood — APPROVED** [review]

**Pull request merged**
